# Generated by Django 3.2.9 on 2022-11-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_restaurants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
