# Generated by Django 4.0.3 on 2022-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=20)),
                ('Genre', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
