# Generated by Django 3.2.9 on 2022-11-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_hotelreview_moviereview_restaurantreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='4', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
