# Generated by Django 4.0.3 on 2022-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221125_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='link',
            field=models.URLField(default='https://www.tripadvisor.in/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(default='https://www.imdb.com/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.URLField(default='https://www.tripadvisor.in/'),
        ),
    ]
