# Generated by Django 4.0.3 on 2022-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_hotel_prange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='prange',
            field=models.TextField(default='2,500-5,000', max_length=200),
        ),
    ]
